### ISSUE TITLE
sopcast not working anymore

### ISSUE THREAD

**Issue by Githeo** [tvaddonsco/program.plexus#1]
Hello, since some new versions sopcast doesn't work anymore. I use Plexus on a raspberry pi 3 inside kodi 17. 
Executing the bundled sopcast client from the command line it works as expected but not inside kodi.

**Comment by grungestranger** [comment]
Hi. I have the same problem. Change the file /opt/retropie/configs/ports/kodi/addons/program.plexus/resources/plexus/sopcast.py to the file from this archive [sopcast.zip](https://github.com/tvaddonsco/program.plexus/files/1691617/sopcast.zip) .
**Developers, Please pay attention to this problem.**
This file from the version **0.1.7b**. I found this version on the Internet. I can't find this version on github.

**Comment by Githeo** [comment]
thanks @grungestranger, it works again. 
I think the one you posted is a precedent version (which on by the way?). It can start the video, but if for any reason the video crashes, we cannot open a new stream as the process in background is still running. I suggest to add a '-9' to the 'kill' commands in your file.

**Comment by tvaddonsco** [comment]
@Githeo would you want to submit a pull request with the functional code?

**Comment by Githeo** [comment]
ok, I'll do it.

**Comment by tvaddonsco** [comment]
@Githeo anyone can submit a pull request already!

**Comment by Githeo** [comment]
Cool. Done.

**Comment by tvaddonsco** [comment]
We've just merged the PR. Any chance you could get in touch via email? We were hoping to get your input as to what else needs to be fixed or updated in Plexus. Thank you again! @Githeo and @grungestranger
